"""PostgreSQL persistence layer for users, analyses, and reset codes."""

from __future__ import annotations

import json
import os
from threading import Lock
import uuid
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

import psycopg
import streamlit as st
from psycopg.rows import dict_row

from backend.model_config import get_model_base_key

LOCAL_TIMEZONE = ZoneInfo("Europe/Bucharest")
DISPLAY_TIMESTAMP_FORMAT = "%d %B %Y, %H:%M"
POSTGRES_INIT_LOCK_ID = 73026101

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    input_text TEXT NOT NULL,
    active_model_key TEXT,
    active_model_id TEXT,
    predicted_label TEXT,
    display_label TEXT,
    confidence DOUBLE PRECISION,
    confidence_level TEXT,
    confidence_message TEXT,
    confidence_margin DOUBLE PRECISION,
    score_self_monitor DOUBLE PRECISION,
    score_consult_gp DOUBLE PRECISION,
    score_urgent DOUBLE PRECISION,
    medquad_context_json TEXT
);

CREATE TABLE IF NOT EXISTS password_reset_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token_hash TEXT UNIQUE NOT NULL,
    user_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_analysis_history_user_id
ON analysis_history(user_id);

CREATE INDEX IF NOT EXISTS idx_analysis_history_user_id_id
ON analysis_history(user_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_password_reset_codes_email
ON password_reset_codes(email);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_token_hash
ON auth_sessions(session_token_hash);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id
ON auth_sessions(user_id);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
"""


def _local_now_display() -> str:
    return datetime.now(LOCAL_TIMEZONE).strftime(DISPLAY_TIMESTAMP_FORMAT)


def _format_timestamp_for_display(value: str) -> str:
    if value is None:
        return value
    try:
        parsed = datetime.fromisoformat(value)
    except (ValueError, TypeError):
        return value

    return parsed.astimezone(LOCAL_TIMEZONE).strftime(DISPLAY_TIMESTAMP_FORMAT)


def _parse_display_timestamp(value: str) -> datetime | None:
    try:
        return datetime.strptime(value, DISPLAY_TIMESTAMP_FORMAT).replace(
            tzinfo=LOCAL_TIMEZONE
        )
    except (TypeError, ValueError):
        return None


def _get_database_url() -> str:
    env_url = os.getenv("SORTMED_DATABASE_URL")
    if env_url:
        return env_url

    try:
        database_config = st.secrets.get("database", {})
    except Exception:
        database_config = {}

    secrets_url = database_config.get("url")
    if secrets_url:
        return str(secrets_url)

    raise RuntimeError(
        "Supabase PostgreSQL is not configured. Add [database].url in Streamlit secrets."
    )


def get_database_backend() -> str:
    return "postgres"


def _execute(connection: Any, query: str, params: tuple[Any, ...] = ()):
    return connection.execute(query, params)


def _execute_script(connection: Any, script: str) -> None:
    for statement in script.split(";"):
        statement = statement.strip()
        if statement:
            connection.execute(statement)


def is_integrity_error(error: Exception) -> bool:
    return isinstance(error, psycopg.IntegrityError)


def _migrate_display_timestamps(
    connection: Any,
    table_name: str,
    column_name: str,
) -> None:
    rows = _execute(
        connection,
        f"SELECT id, {column_name} FROM {table_name}",
    ).fetchall()

    for row in rows:
        if row[column_name] is None:
            continue
        formatted_timestamp = _format_timestamp_for_display(row[column_name])
        if formatted_timestamp == row[column_name]:
            continue

        _execute(
            connection,
            f"UPDATE {table_name} SET {column_name} = %s WHERE id = %s",
            (formatted_timestamp, row["id"]),
        )


def _row_to_dict(row: Any | None) -> dict[str, Any] | None:
    if row is None:
        return None
    return dict(row)


def _to_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def get_connection() -> Any:
    return psycopg.connect(_get_database_url(), row_factory=dict_row)


def init_db() -> None:
    with get_connection() as connection:
        _execute(connection, "SELECT pg_advisory_xact_lock(%s)", (POSTGRES_INIT_LOCK_ID,))
        _execute_script(connection, POSTGRES_SCHEMA_SQL)
        _migrate_display_timestamps(connection, "profiles", "created_at")
        _migrate_display_timestamps(connection, "analysis_history", "timestamp")
        _migrate_display_timestamps(connection, "password_reset_codes", "created_at")
        _migrate_display_timestamps(connection, "password_reset_codes", "used_at")
        _migrate_display_timestamps(connection, "password_reset_codes", "expires_at")
        _migrate_display_timestamps(connection, "auth_sessions", "created_at")
        _migrate_display_timestamps(connection, "auth_sessions", "expires_at")
        _migrate_display_timestamps(connection, "auth_sessions", "last_seen_at")
        connection.commit()


_db_initialized = False
_db_init_lock = Lock()


def ensure_db_initialized() -> None:
    """Call init_db() at most once per Python process."""
    global _db_initialized
    with _db_init_lock:
        if not _db_initialized:
            init_db()
            _db_initialized = True


def create_user(
    first_name: str,
    last_name: str,
    email: str,
    password_hash: str,
) -> dict[str, Any]:
    user_id = str(uuid.uuid4())
    created_at = _local_now_display()

    with get_connection() as connection:
        _execute(
            connection,
            """
            INSERT INTO profiles (
                user_id, first_name, last_name, email, password_hash, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s)
            """,
            (user_id, first_name, last_name, email, password_hash, created_at),
        )
        connection.commit()

    user = get_user_by_id(user_id)
    if user is None:
        raise RuntimeError("User was created but could not be loaded.")
    return user


def get_user_by_email(email: str) -> dict[str, Any] | None:
    with get_connection() as connection:
        row = _execute(
            connection,
            "SELECT * FROM profiles WHERE email = %s",
            (email,),
        ).fetchone()
    return _row_to_dict(row)


def get_user_by_id(user_id: str) -> dict[str, Any] | None:
    with get_connection() as connection:
        row = _execute(
            connection,
            "SELECT * FROM profiles WHERE user_id = %s",
            (user_id,),
        ).fetchone()
    return _row_to_dict(row)


def create_auth_session(
    user_id: str,
    session_token_hash: str,
    expires_at: str,
) -> None:
    now = _local_now_display()

    with get_connection() as connection:
        _execute(
            connection,
            """
            INSERT INTO auth_sessions (
                session_token_hash, user_id, created_at, expires_at, last_seen_at
            )
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (session_token_hash)
            DO UPDATE SET
                user_id = EXCLUDED.user_id,
                expires_at = EXCLUDED.expires_at,
                last_seen_at = EXCLUDED.last_seen_at
            """,
            (session_token_hash, user_id, now, expires_at, now),
        )
        connection.commit()


def get_active_auth_session(session_token_hash: str) -> dict[str, Any] | None:
    with get_connection() as connection:
        row = _execute(
            connection,
            """
            SELECT
                p.id,
                p.user_id,
                p.first_name,
                p.last_name,
                p.email,
                p.created_at,
                s.expires_at AS session_expires_at
            FROM auth_sessions s
            JOIN profiles p ON p.user_id = s.user_id
            WHERE s.session_token_hash = %s
            """,
            (session_token_hash,),
        ).fetchone()

    record = _row_to_dict(row)
    if record is None:
        return None

    expires_at = _parse_display_timestamp(record["session_expires_at"])
    if expires_at is None or expires_at <= datetime.now(LOCAL_TIMEZONE):
        delete_auth_session(session_token_hash)
        return None

    touch_auth_session(session_token_hash)
    return record


def touch_auth_session(session_token_hash: str) -> None:
    with get_connection() as connection:
        _execute(
            connection,
            "UPDATE auth_sessions SET last_seen_at = %s WHERE session_token_hash = %s",
            (_local_now_display(), session_token_hash),
        )
        connection.commit()


def delete_auth_session(session_token_hash: str) -> None:
    with get_connection() as connection:
        _execute(
            connection,
            "DELETE FROM auth_sessions WHERE session_token_hash = %s",
            (session_token_hash,),
        )
        connection.commit()


def delete_auth_sessions_for_user(user_id: str) -> None:
    with get_connection() as connection:
        _execute(
            connection,
            "DELETE FROM auth_sessions WHERE user_id = %s",
            (user_id,),
        )
        connection.commit()


def save_analysis(user_id: str, input_text: str, analysis: dict[str, Any]) -> int:
    scores = analysis.get("scores") or {}
    medquad_context_json = json.dumps(
        analysis.get("context", []),
        ensure_ascii=False,
    )

    with get_connection() as connection:
        cursor = _execute(
            connection,
            """
            INSERT INTO analysis_history (
                user_id,
                timestamp,
                input_text,
                active_model_key,
                active_model_id,
                predicted_label,
                display_label,
                confidence,
                confidence_level,
                confidence_message,
                confidence_margin,
                score_self_monitor,
                score_consult_gp,
                score_urgent,
                medquad_context_json
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                user_id,
                _local_now_display(),
                input_text,
                analysis.get("active_model_key"),
                analysis.get("active_model_id"),
                analysis.get("label"),
                analysis.get("result"),
                _to_float(analysis.get("confidence")),
                analysis.get("confidence_level"),
                analysis.get("confidence_message"),
                _to_float(analysis.get("confidence_margin")),
                _to_float(scores.get("self_monitor")),
                _to_float(scores.get("consult_gp")),
                _to_float(scores.get("urgent")),
                medquad_context_json,
            ),
        )
        new_id = cursor.fetchone()["id"]
        connection.commit()
        return int(new_id)


def get_user_account_statistics(user_id: str) -> dict[str, Any]:
    with get_connection() as connection:
        agg = _execute(
            connection,
            """
            SELECT
                COUNT(*) AS total_analyses,
                COUNT(DISTINCT active_model_key) AS models_used_count,
                AVG(confidence) AS avg_confidence,
                MAX(confidence) AS max_confidence,
                SUM(CASE WHEN predicted_label = 'urgent' THEN 1 ELSE 0 END) AS urgent_count,
                SUM(CASE WHEN predicted_label = 'consult_gp' THEN 1 ELSE 0 END) AS consult_gp_count,
                SUM(CASE WHEN predicted_label = 'self_monitor' THEN 1 ELSE 0 END) AS self_monitor_count,
                ROUND(AVG(
                    LENGTH(TRIM(input_text))
                    - LENGTH(REPLACE(TRIM(input_text), ' ', ''))
                    + 1
                )) AS avg_word_count,
                SUM(CASE WHEN confidence_level = 'high' THEN 1 ELSE 0 END) AS conf_high,
                SUM(CASE WHEN confidence_level = 'medium' THEN 1 ELSE 0 END) AS conf_medium,
                SUM(CASE WHEN confidence_level = 'low' THEN 1 ELSE 0 END) AS conf_low
            FROM analysis_history
            WHERE user_id = %s
            """,
            (user_id,),
        ).fetchone()

        first_row = _execute(
            connection,
            "SELECT timestamp FROM analysis_history WHERE user_id = %s ORDER BY id ASC LIMIT 1",
            (user_id,),
        ).fetchone()

        latest_row = _execute(
            connection,
            "SELECT timestamp FROM analysis_history WHERE user_id = %s ORDER BY id DESC LIMIT 1",
            (user_id,),
        ).fetchone()

        rec_row = _execute(
            connection,
            """
            SELECT display_label, COUNT(*) AS cnt
            FROM analysis_history
            WHERE user_id = %s AND display_label IS NOT NULL
            GROUP BY display_label
            ORDER BY cnt DESC
            LIMIT 1
            """,
            (user_id,),
        ).fetchone()

        model_breakdown_rows = _execute(
            connection,
            """
            SELECT active_model_key, COUNT(*) AS cnt
            FROM analysis_history
            WHERE user_id = %s AND active_model_key IS NOT NULL
            GROUP BY active_model_key
            """,
            (user_id,),
        ).fetchall()

    stats: dict[str, Any] = dict(agg) if agg else {}
    model_breakdown: dict[str, int] = {}
    for row in model_breakdown_rows:
        model_key = row["active_model_key"]
        base_key = get_model_base_key(model_key) or model_key
        model_breakdown[base_key] = model_breakdown.get(base_key, 0) + int(row["cnt"])

    stats["first_analysis_date"] = first_row["timestamp"] if first_row else None
    stats["latest_analysis_date"] = latest_row["timestamp"] if latest_row else None
    stats["models_used_count"] = len(model_breakdown)
    stats["most_used_model"] = (
        max(model_breakdown.items(), key=lambda item: item[1])[0]
        if model_breakdown
        else None
    )
    stats["most_common_recommendation"] = rec_row["display_label"] if rec_row else None
    stats["model_breakdown"] = model_breakdown
    return stats


def delete_user_account(user_id: str, email: str) -> bool:
    with get_connection() as connection:
        _execute(
            connection,
            "DELETE FROM auth_sessions WHERE user_id = %s",
            (user_id,),
        )
        _execute(
            connection,
            "DELETE FROM analysis_history WHERE user_id = %s",
            (user_id,),
        )
        _execute(
            connection,
            "DELETE FROM password_reset_codes WHERE email = %s",
            (email,),
        )
        cursor = _execute(
            connection,
            "DELETE FROM profiles WHERE user_id = %s",
            (user_id,),
        )
        connection.commit()
        return cursor.rowcount > 0


def get_user_analysis_history(user_id: str, limit: int = 200) -> list[dict[str, Any]]:
    with get_connection() as connection:
        rows = _execute(
            connection,
            """
            SELECT *
            FROM analysis_history
            WHERE user_id = %s
            ORDER BY id DESC
            LIMIT %s
            """,
            (user_id, limit),
        ).fetchall()
    return [dict(row) for row in rows]

def create_reset_code(email: str, code_hash: str, expires_at: str) -> None:
    with get_connection() as connection:
        _execute(
            connection,
            "UPDATE password_reset_codes SET used_at = %s WHERE email = %s AND used_at IS NULL",
            (_local_now_display(), email),
        )
        _execute(
            connection,
            """
            INSERT INTO password_reset_codes (email, code_hash, expires_at, created_at)
            VALUES (%s, %s, %s, %s)
            """,
            (email, code_hash, expires_at, _local_now_display()),
        )
        connection.commit()


def get_active_reset_code(email: str) -> dict[str, Any] | None:
    with get_connection() as connection:
        rows = _execute(
            connection,
            """
            SELECT * FROM password_reset_codes
            WHERE email = %s AND used_at IS NULL AND attempts < 5
            ORDER BY id DESC
            """,
            (email,),
        ).fetchall()

    now = datetime.now(LOCAL_TIMEZONE)
    for row in rows:
        record = _row_to_dict(row)
        try:
            expires_at = datetime.strptime(
                record["expires_at"], DISPLAY_TIMESTAMP_FORMAT
            ).replace(tzinfo=LOCAL_TIMEZONE)
            if expires_at > now:
                return record
        except (ValueError, KeyError):
            pass
    return None


def increment_reset_attempts(code_id: int) -> None:
    with get_connection() as connection:
        _execute(
            connection,
            "UPDATE password_reset_codes SET attempts = attempts + 1 WHERE id = %s",
            (code_id,),
        )
        connection.commit()


def mark_reset_code_used(code_id: int) -> None:
    with get_connection() as connection:
        _execute(
            connection,
            "UPDATE password_reset_codes SET used_at = %s WHERE id = %s",
            (_local_now_display(), code_id),
        )
        connection.commit()


def update_user_password(email: str, password_hash: str) -> bool:
    with get_connection() as connection:
        cursor = _execute(
            connection,
            "UPDATE profiles SET password_hash = %s WHERE email = %s",
            (password_hash, email),
        )
        connection.commit()
        return cursor.rowcount > 0
